# Generated by Django 5.0.4 on 2024-05-01 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_phone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_construction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('number_rooms', models.IntegerField(blank=True, null=True)),
                ('number_bathrooms', models.IntegerField(blank=True, null=True)),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('total_ground', models.FloatField(blank=True, null=True)),
                ('year_construction', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amenities_list', models.TextField(blank=True, null=True)),
                ('owner_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_owner', to='house.owner')),
                ('type_construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_typeConstruction', to='house.typeconstruction')),
            ],
        ),
    ]
