# Generated by Django 5.0.4 on 2024-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
